version: "3.9"

services:
  web:
    build: .
    container_name: scheduler-and-api-backend
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000 --noreload"
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - type: bind
        source: ./bitcoindb.sqlite3
        target: /code/bitcoindb.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - .env
