# Generated by Django 3.2.13 on 2022-05-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitCoinPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('coin', models.CharField(default='btc', max_length=100)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
